// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace CommercialWorkplacesFix
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "CommercialWorkplacesFix";
        public const string Version     = "1.0.1";
        public const string Title       = "Commercial Workplaces Fix";
        public const string Description = "Fix for commercial company workplaces never increasing.";
    }
}
